#!/usr/bin/env ruby
require 'colorize'
require 'cli/ui'
CLI::UI::Prompt.ask('==> Better-Apt:  Select an option:') do |handler|
  handler.option('install')  { |selection| selection; system("bapt-install") }
  handler.option('uninstall')     { |selection| selection; system("bapt-uninstall") }
  handler.option('search')   { |selection| selection; system("bapt-search") }
  handler.option('update') { |selection| selection; system("bapt-update") }
end
